In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.Successfully installed absl-py-1.2.0 astunparse-1.6.3 flatbuffers-2.0.7 gast-0.4.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 keras-2.10.0 keras-preprocessing-1.1.2 libclang-14.0.6 oauthlib-3.2.1 opt-einsum-3.3.0 requests-oauthlib-1.3.1 tensorboard-2.10.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tensorflow-2.10.0 tensorflow-estimator-2.10.0 tensorflow-io-gcs-filesystem-0.27.0 termcolor-2.0.1



In [4]:
tf.__version__

'2.10.0'

# Data Preprocessing


In [5]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [6]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [11]:
x = dataset.iloc[:,3:-1].values

In [16]:
y = dataset.iloc[:,-1].values

In [14]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [17]:
print(y)

[1 0 1 ... 1 1 0]


# Encoding Categorical Data

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()


In [20]:
x[:,2] = le.fit_transform(x[:,2])

In [21]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


## One Hot Encoding for "Geography" Column

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [23]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')

In [24]:
x = np.array(ct.fit_transform(x))

In [25]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Spliting the dataset into training and test set

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size= 0.2, random_state=0)

# Feature Scaling -  It is must in Deep Learning

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
sc = StandardScaler()


In [30]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## Building the ANN

In [31]:
ann = tf.keras.models.Sequential() 
#Initialize the ANN

In [32]:
#Adding the input layer & First Hidden Layer

ann.add(tf.keras.layers.Dense(units=6,activation='relu'))  # no. of neurons is 6, activation function is RECTIFIER Func

# how do we decide the no. of neurons -there is no rule, we have to decide it, Based on experiment

In [34]:
#Adding the Second hidden Layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [35]:
#Adding the output Layer

ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

In [37]:
#Compiling the ANN
ann.compile(optimizer='adam', loss= 'binary_crossentropy', metrics = ['accuracy'])

In [38]:
#Training the ANN on the Training set
ann.fit(x_train,y_train, batch_size= 32 , epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 693us/step - loss: 0.5111 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 0s 702us/step - loss: 0.4486 - accuracy: 0.7962
Epoch 3/100
250/250 [==============================] - 0s 728us/step - loss: 0.4279 - accuracy: 0.8019
Epoch 4/100
250/250 [==============================] - 0s 727us/step - loss: 0.4114 - accuracy: 0.8125
Epoch 5/100
250/250 [==============================] - 0s 667us/step - loss: 0.3969 - accuracy: 0.8279
Epoch 6/100
250/250 [==============================] - 0s 671us/step - loss: 0.3853 - accuracy: 0.8360
Epoch 7/100
250/250 [==============================] - 0s 699us/step - loss: 0.3776 - accuracy: 0.8395
Epoch 8/100
250/250 [==============================] - 0s 654us/step - loss: 0.3704 - accuracy: 0.8444
Epoch 9/100
250/250 [==============================] - 0s 659us/step - loss: 0.3642 - accuracy: 0.8453
Epoch 10/100
250/250 [==============================] - 0s 665us/step - l

Epoch 80/100
250/250 [==============================] - 0s 969us/step - loss: 0.3355 - accuracy: 0.8624
Epoch 81/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3354 - accuracy: 0.8630
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3358 - accuracy: 0.8627
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3352 - accuracy: 0.8621
Epoch 84/100
250/250 [==============================] - 0s 987us/step - loss: 0.3352 - accuracy: 0.8635
Epoch 85/100
250/250 [==============================] - 0s 942us/step - loss: 0.3353 - accuracy: 0.8635
Epoch 86/100
250/250 [==============================] - 0s 893us/step - loss: 0.3348 - accuracy: 0.8629
Epoch 87/100
250/250 [==============================] - 0s 952us/step - loss: 0.3350 - accuracy: 0.8633
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3347 - accuracy: 0.8630
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - lo

In [40]:
print(ann.predict(sc.transform([[0,1,0,600,1,40,3,90000,2,1,1,50000]])) >0.5)

1/1 [==============================] - 0s 27ms/step
[[False]]


## predicting the test set result

In [41]:
y_pred = ann.predict(x_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 554us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making Confusion Matrix

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1513   82]
 [ 200  205]]


0.859